name: 'Mark stale pull requests'
on:
  schedule:
    # Run every 6 hours at xx:30.
    - cron: '30 */6 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/stale@v9
        with:
          # Get PRs in ascending (oldest first) order.
          ascending: true
          operations-per-run: 50
          # PRs: Mark as stale after 2 months, close after 1 month more
          days-before-pr-stale: 60
          days-before-pr-close: 31
          delete-branch: true
          # Label to use when marking a PR as stale
          stale-pr-label: '[Status] Stale'
          # PRs with these labels will never be considered stale.
          exempt-pr-labels: '[Pri] High,[Pri] BLOCKER,[Status] Keep Open'
          # Message to be added to stale PRs.
          stale-pr-message: |
            <p>This PR has been marked as stale. This happened because:</p>

            <ul>
              <li>It has been inactive for the past 3 months.</li>
              <li>It hasn't been labeled `[Pri] BLOCKER`, `[Pri] High`, `[Status] Keep Open`, etc.</li>
            </ul>

            <p>If this PR is still useful, please do a trunk merge or rebase
            and otherwise make sure it's up to date and has clear testing instructions.
            You may also want to ping possible reviewers in case they've forgotten about it.
            Please close this PR if you think it's not valid anymore — if you
            do, please add a brief explanation.</p>

            <p>If the PR is not updated (or at least commented on) in another month, it will be automatically closed.</p>
          close-pr-message: |
            <p>This PR has been automatically closed as it has not been updated in some time.
            If you want to resume work on the PR, feel free to restore the branch and reopen the PR.</p>
          # Ignore issues, only operating on pull requests.
          days-before-issue-stale: -1
          days-before-issue-close: -1